<?php

namespace App\Filament\Resources\ExamQuestionPapers\Tables;

use App\Filament\Resources\Exams\ExamResource;
use App\Models\ExamQuestionPaper;
use App\Models\QuestionBankItem;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Notifications\Notification;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class ExamQuestionPapersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('exam.name')
                    ->label('Exam')
                    ->searchable()
                    ->sortable()
                    ->weight('medium')
                    ->url(fn(ExamQuestionPaper $record) => ExamResource::getUrl('view', ['record' => $record->exam]))
                    ->openUrlInNewTab(),

                TextColumn::make('examSubject.subject.name')
                    ->label('Subject')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('questionBank.name')
                    ->label('Question Bank')
                    ->badge()
                    ->color('primary'),

                TextColumn::make('total_marks')
                    ->label('Total Marks')
                    ->badge()
                    ->color('success')
                    ->sortable(),

                TextColumn::make('question_count')
                    ->label('Questions')
                    ->getStateUsing(fn(ExamQuestionPaper $record) => count($record->selected_questions ?? []))
                    ->badge()
                    ->color('gray'),

                IconColumn::make('is_shuffled')
                    ->label('Shuffled')
                    ->boolean()
                    ->trueIcon('heroicon-o-arrow-path')
                    ->falseIcon('heroicon-o-bars-3')
                    ->trueColor('info')
                    ->falseColor('gray'),

                TextColumn::make('generator.name')
                    ->label('Generated By')
                    ->placeholder('—')
                    ->toggleable(isToggledHiddenByDefault: true),

                TextColumn::make('created_at')
                    ->label('Created')
                    ->dateTime('d M Y H:i')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('created_at', 'desc')
            ->filters([
                SelectFilter::make('exam_id')
                    ->label('Exam')
                    ->relationship('exam', 'name')
                    ->searchable()
                    ->preload(),

                SelectFilter::make('question_bank_id')
                    ->label('Question Bank')
                    ->relationship('questionBank', 'name')
                    ->searchable()
                    ->preload(),
            ])
            ->recordActionsColumnLabel('Actions')
            ->recordActions([
                ActionGroup::make([
                    ViewAction::make()
                        ->icon('heroicon-o-eye')
                        ->color('info'),

                    EditAction::make()
                        ->icon('heroicon-o-pencil')
                        ->color('primary'),

                    Action::make('print_paper')
                        ->label('Print Paper')
                        ->icon('heroicon-o-printer')
                        ->color('success')
                        ->url(fn(ExamQuestionPaper $record) => route('exams.question-paper', [
                            'exam' => $record->exam,
                            'examSubject' => $record->exam_subject_id,
                        ]))
                        ->openUrlInNewTab()
                        ->visible(fn(ExamQuestionPaper $record) => $record->questions->isNotEmpty()),

                    Action::make('regenerate')
                        ->label('Regenerate from Bank')
                        ->icon('heroicon-o-arrow-path')
                        ->color('warning')
                        ->requiresConfirmation()
                        ->modalDescription('This will replace all currently selected questions with a new random pick from the bank.')
                        ->action(function (ExamQuestionPaper $record) {
                            $questions = QuestionBankItem::query()
                                ->where('question_bank_id', $record->question_bank_id)
                                ->where('is_active', true)
                                ->inRandomOrder()
                                ->limit(count($record->selected_questions ?? []) ?: 10)
                                ->get();

                            $record->update([
                                'selected_questions' => $questions->pluck('marks', 'id')->toArray(),
                            ]);

                            Notification::make()
                                ->title('Paper regenerated')
                                ->success()
                                ->send();
                        }),

                    DeleteAction::make()
                        ->icon('heroicon-o-trash')
                        ->color('danger')
                        ->requiresConfirmation(),
                ])
                ->dropdownPlacement('bottom-start'),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateIcon('heroicon-o-document-text')
            ->emptyStateHeading('No question papers generated yet')
            ->emptyStateDescription('Create a paper by selecting an exam subject and question bank.');
    }
}
