<?php

namespace App\Filament\Resources\FormTemplates\Schemas;

use App\Models\FormTemplate;
use App\Models\User;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Illuminate\Validation\Rule;
use Illuminate\Support\Str;

class FormTemplateForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('branch_id')
                    ->label('Select Branch')
                    ->relationship('branch', 'name')
                    ->searchable()
                    ->preload()
                    ->live()
                    ->afterStateUpdated(fn (Set $set) => $set('user_id', null))
                    ->required()
                    ->rule(function ($record) {
                        return Rule::unique('form_templates', 'branch_id')
                            ->ignore($record?->id);
                    })
                    ->validationMessages([
                        'unique' => 'This branch already has a form template.',
                    ]),
                // TextInput::make('active_version_id')
                //     ->numeric(),
                Select::make('user_id')
                    ->label('Select User')
                    ->options(function (Get $get): array {
                        $branchId = $get('branch_id');

                        if (! $branchId) {
                            return [];
                        }

                        return User::whereHas('branch', function ($query) use ($branchId) {
                                $query->where('branches.id', $branchId);
                            })
                            ->pluck('name', 'id')
                            ->toArray();
                    })
                    ->searchable()
                    ->preload()
                    ->required()
                    ->placeholder('Select a user'),

                TextInput::make('registration_serial')
                    ->required(),
                TextInput::make('name')
                    ->required()
                    ->live(onBlur: true)
                    ->afterStateUpdated(function (Set $set, ?string $state, ?FormTemplate $record) {
                        $set('slug', self::generateUniqueSlug($state ?? '', $record?->id));
                    }),
                TextInput::make('slug')
                    ->required()
                    ->readOnly()
                    ->dehydrated(),
                Select::make('type')
                    ->options(['admission' => 'Admission'])
                    ->default('admission')
                    ->required(),
                Select::make('status')
                    ->options(['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'])
                    ->default('draft')
                    ->required(),
                TextInput::make('form_layout')
                    ->required()
                    ->default('default'),
                Select::make('rollno_generation_scope')
                    ->label('Roll Number Generated By')
                    ->options(['class' => 'Class', 'section' => 'Section'])
                    ->default('section')
                    ->required(),
                Toggle::make('is_active')
                    ->required()
                    ->columnSpanFull(),
            ]);
    }

    public static function generateUniqueSlug(string $name, ?int $ignoreId = null): string
    {
        $slug = Str::slug($name);
        $originalSlug = $slug;
        $count = 1;

        while (
            FormTemplate::where('slug', $slug)
                ->when($ignoreId, fn ($query) => $query->where('id', '!=', $ignoreId))
                ->exists()
        ) {
            $slug = $originalSlug . '-' . $count++;
        }

        return $slug;
    }    
}
