<?php

namespace App\Filament\Resources\FormTemplates\Schemas;

use App\Models\FormTemplate;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class FormTemplateInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Form Template')
                    ->description('Basic information about this admission form template.')
                    ->icon('heroicon-o-document-text')
                    ->schema([
                        Grid::make([
                            'default' => 1,
                            'sm' => 2,
                            'lg' => 3,
                        ])
                            ->schema([
                                TextEntry::make('name')
                                    ->label('Template Name')
                                    ->icon('heroicon-o-document-text')
                                    ->weight('bold')
                                    ->size('lg')
                                    ->placeholder('-'),

                                TextEntry::make('branch.name')
                                    ->label('Branch')
                                    ->icon('heroicon-o-building-office')
                                    ->weight('medium')
                                    ->placeholder('-'),

                                TextEntry::make('user.name')
                                    ->label('Created By')
                                    ->icon('heroicon-o-user')
                                    ->placeholder('-'),

                                TextEntry::make('registration_serial')
                                    ->label('Registration Prefix')
                                    ->badge()
                                    ->icon('heroicon-o-hashtag')
                                    ->placeholder('-'),

                                TextEntry::make('type')
                                    ->label('Template Type')
                                    ->badge()
                                    ->color('info')
                                    ->placeholder('-'),

                                TextEntry::make('status')
                                    ->label('Template Status')
                                    ->badge()
                                    ->color(
                                        fn (?string $state): string => match ($state) {
                                            'published' => 'success',
                                            'draft' => 'warning',
                                            'archived' => 'gray',
                                            default => 'gray',
                                        }
                                    )
                                    ->placeholder('-'),

                                IconEntry::make('is_active')
                                    ->label('Template Active')
                                    ->boolean()
                                    ->trueIcon('heroicon-o-check-circle')
                                    ->falseIcon('heroicon-o-x-circle'),

                                TextEntry::make('slug')
                                    ->label('Form Slug')
                                    ->copyable()
                                    ->copyMessage('Slug copied')
                                    ->icon('heroicon-o-link')
                                    ->placeholder('-')
                                    ->columnSpan([
                                        'sm' => 1,
                                        'lg' => 2,
                                    ]),
                            ]),
                    ]),

                Section::make('Form Configuration')
                    ->description('Printing and roll number generation settings.')
                    ->icon('heroicon-o-cog-6-tooth')
                    ->schema([
                        Grid::make([
                            'default' => 1,
                            'sm' => 2,
                            'lg' => 3,
                        ])
                            ->schema([
                                TextEntry::make('form_layout')
                                    ->label('Print Layout')
                                    ->badge()
                                    ->color('info')
                                    ->icon('heroicon-o-printer')
                                    ->placeholder('-'),

                                TextEntry::make('rollno_generation_scope')
                                    ->label('Roll Number Generated By')
                                    ->formatStateUsing(
                                        fn (?string $state): string => match ($state) {
                                            'class' => 'Class',
                                            'section' => 'Section',
                                            default => $state ?? '-',
                                        }
                                    )
                                    ->badge()
                                    ->color('primary')
                                    ->icon('heroicon-o-hashtag')
                                    ->placeholder('-'),

                                TextEntry::make('active_version_id')
                                    ->label('Active Version')
                                    ->numeric()
                                    ->placeholder('-'),
                            ]),
                    ]),

                Section::make('Record Information')
                    ->description('System information and timestamps.')
                    ->icon('heroicon-o-information-circle')
                    ->schema([
                        Grid::make([
                            'default' => 1,
                            'sm' => 2,
                        ])
                            ->schema([
                                TextEntry::make('created_at')
                                    ->label('Created At')
                                    ->dateTime('d M Y, h:i A')
                                    ->placeholder('-'),

                                TextEntry::make('updated_at')
                                    ->label('Last Updated')
                                    ->dateTime('d M Y, h:i A')
                                    ->placeholder('-'),
                            ]),
                    ])
                    ->collapsible()
                    ->collapsed(),
            ]);
    }
}