<?php

namespace App\Filament\Resources\FormTemplates\Schemas;

use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Illuminate\Database\Eloquent\Builder;

class FormTemplateForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('branch_id')
                    ->label('Select Branch')
                    ->relationship('branch', 'name')
                    ->searchable()
                    ->preload()
                    ->live()
                    ->afterStateUpdated(fn (Set $set) => $set('user_id', null))
                    ->required()
                    ->placeholder('Select a branch'),
                // TextInput::make('active_version_id')
                //     ->numeric(),
                Select::make('user_id')
                    ->label('Select User')
                    ->relationship(
                        name: 'user',
                        titleAttribute: 'name',
                        modifyQueryUsing: fn (Builder $query, Get $get) => $query
                            ->whereHas('teacherProfile', fn (Builder $q) => $q
                                ->where('branch_id', $get('branch_id'))
                            )
                    )
                    ->searchable()
                    ->preload()
                    ->required()
                    ->placeholder('Select a user'),
                TextInput::make('registration_serial')
                    ->required(),
                TextInput::make('name')
                    ->required(),
                TextInput::make('slug')
                    ->required(),
                Select::make('type')
                    ->options(['admission' => 'Admission'])
                    ->default('admission')
                    ->required(),
                Select::make('status')
                    ->options(['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'])
                    ->default('draft')
                    ->required(),
                TextInput::make('form_layout')
                    ->required()
                    ->default('default'),
                Select::make('rollno_generation_scope')
                    ->label('Roll Number Generated By')
                    ->options(['class' => 'Class', 'section' => 'Section'])
                    ->default('section')
                    ->required(),
                Toggle::make('is_active')
                    ->required()
                    ->columnSpanFull(),
            ]);
    }
}
