<?php

namespace App\Filament\Resources\FormTemplates\Schemas;

use App\Models\FormTemplate;
use App\Models\User;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Illuminate\Validation\Rule;
use Illuminate\Support\Str;

class FormTemplateForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('branch_id')
                    ->label('Select Branch')
                    ->relationship('branch', 'name')
                    ->searchable()
                    ->preload()
                    ->live()
                    ->afterStateUpdated(fn (Set $set) => $set('user_id', null))
                    ->required()
                    ->rule(function ($record) {
                        return Rule::unique('form_templates', 'branch_id')
                            ->ignore($record?->id);
                    })
                    ->validationMessages([
                        'unique' => 'This branch already has a form template.',
                    ]),
                // TextInput::make('active_version_id')
                //     ->numeric(),
                Select::make('user_id')
                    ->label('Select User')
                    ->options(function (Get $get): array {
                        $branchId = $get('branch_id');

                        if (! $branchId) {
                            return [];
                        }

                        return User::whereHas('branch', function ($query) use ($branchId) {
                                $query->where('branches.id', $branchId);
                            })
                            ->pluck('name', 'id')
                            ->toArray();
                    })
                    ->searchable()
                    ->preload()
                    ->required()
                    ->placeholder('Select a user'),

                TextInput::make('registration_serial')
                    ->required(),
                TextInput::make('name')
                    ->required()
                    ->live(onBlur: true)
                    ->afterStateUpdated(function (Set $set, ?string $state, ?FormTemplate $record) {
                        $set('slug', self::generateUniqueSlug($state ?? '', $record?->id));
                    }),
                TextInput::make('slug')
                    ->required()
                    ->readOnly()
                    ->dehydrated(),
                Select::make('type')
                    ->options(['admission' => 'Admission'])
                    ->default('admission')
                    ->required(),
                Select::make('status')
                    ->options(['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'])
                    ->default('draft')
                    ->required(),
                Select::make('form_layout')
                    ->label('Print Layout')
                    ->options(self::printLayoutOptions())
                    ->default('default')
                    ->required()
                    ->helperText('Choose the printable admission form layout for this branch.'),
                Select::make('rollno_generation_scope')
                    ->label('Roll Number Generated By')
                    ->options(['class' => 'Class', 'section' => 'Section'])
                    ->default('section')
                    ->required(),
                Toggle::make('is_active')
                    ->required()
                    ->columnSpanFull(),
            ]);
    }

    public static function generateUniqueSlug(string $name, ?int $ignoreId = null): string
    {
        $slug = Str::slug($name);
        $originalSlug = $slug;
        $count = 1;

        while (
            FormTemplate::where('slug', $slug)
                ->when($ignoreId, fn ($query) => $query->where('id', '!=', $ignoreId))
                ->exists()
        ) {
            $slug = $originalSlug . '-' . $count++;
        }

        return $slug;
    }
    
    public static function printLayoutOptions(): array
    {
        $viewPath = resource_path('views/filament/pages/admission-form-print');

        if (! is_dir($viewPath)) {
            return ['default' => 'Default Layout'];
        }

        $layouts = [];

        foreach (glob($viewPath . '/*.blade.php') as $filePath) {
            $filename = basename($filePath, '.blade.php'); // e.g. "letterhead"

            // Read first 5 lines to find @layout-name metadata comment
            $handle = fopen($filePath, 'r');
            $label  = null;
            $lines  = 0;

            while (($line = fgets($handle)) !== false && $lines < 5) {
                if (preg_match('/@layout-name\s+(.+)/', $line, $matches)) {
                    $label = trim($matches[1]);
                    break;
                }
                $lines++;
            }

            fclose($handle);
            
            $label ??= str(str_replace(['_', '-'], ' ', $filename))->title()->toString();

            $layouts[$filename] = $label;
        }

        // Always ensure 'default' appears first
        uksort($layouts, fn($a) => $a === 'default' ? -1 : 1);

        return $layouts ?: ['default' => 'Default Layout'];
    }
}
