<?php

namespace App\Filament\Resources\FormTemplates\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class FormTemplateInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('branch.name')
                    ->label('Branch name'),
                TextEntry::make('active_version_id')
                    ->label('Form template avtive version')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('user.name')
                    ->label('Form template created by')
                    ->placeholder('-'),
                TextEntry::make('registration_serial')
                    ->label('Registration prefix'),
                TextEntry::make('name')
                    ->label('Form template name'),
                TextEntry::make('slug'),
                TextEntry::make('type')
                    ->label('Form template type'),
                TextEntry::make('status')
                    ->label('Form template status')
                    ->badge(),
                IconEntry::make('is_active')
                    ->label('Is template form active')
                    ->boolean(),
                TextEntry::make('form_layout')
                    ->label('Form template print layout'),
                TextEntry::make('rollno_generation_scope')
                    ->label('Student roll number generated by')
                    ->badge(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
